function assertHandlerContext(context = {}) {
  const missing = [];
  for (const [key, value] of Object.entries(context)) {
    if (key === 'ConfigControl') {
      if (!value || typeof value.get !== 'function') missing.push(`${key}.get`);
      continue;
    }
    if (key === 'logger') {
      if (!value || typeof value.error !== 'function') missing.push(`${key}.error`);
      continue;
    }
    if (typeof value !== 'function') {
      missing.push(key);
    }
  }
  if (missing.length > 0) {
    throw new Error(`Web console handler context is missing: ${missing.join(', ')}`);
  }
}

export function createWebConsoleHandlerContext(options = {}) {
  const {
    ConfigControl,
    logger,
    getWebConsoleConfig,
    listGroupConfigBackups,
    httpUtils = {},
    webConsoleAuth = {},
    fileBrowserConsole = {},
    botPluginConsole = {},
    pluginCatalogConsole = {},
    dependencyConsole = {},
    userDataConsole = {},
    logConsole = {},
    logDiagnosisConsole = { diagnosePayload: async () => ({ success: false, error: '日志排查模块不可用' }) },
    configBackupConsole = {},
    configPayloadConsole = {},
    apiSettingsConsole = {},
    memeConsole = {},
    featureConfigConsole = {},
    imageMonitorConsole = {},
    sandboxConsole = {},
    qqSimulatorConsole = {},
    staticConsole = {},
    usageTrendConsole = {},
    overviewConsole = {},
    pluginSettingsConsole = {},
    remoteImageProxy = {},
    consoleBackground = {},
    groupManagementCommon = {},
    groupManagementEventFeed = {},
    groupWelcomeConsole = {},
    groupManagementPayload = {},
    groupManagementMembers = {},
    groupManagementJoinRequests = {},
    groupManagementMemberWarnings = {},
    groupManagementTitleApplications = {},
    groupManagementConfigSave = {},
    groupManagementBulkActions = {},
    groupManagementSettings = {},
    groupManagementHealthFix = {},
  } = options;

  const context = {
    ConfigControl,
    logger,
    getWebConsoleConfig,
    listGroupConfigBackups,
    addGroupManagementWarningPayload: groupManagementMemberWarnings.addWarningPayload,
    applyGroupManagementHealthFixPayload: groupManagementHealthFix.applyPayload,
    approveGroupManagementJoinRequestPayload: groupManagementJoinRequests.approvePayload,
    approveGroupManagementTitleApplicationPayload: groupManagementTitleApplications.approvePayload,
    buildAffinityHistoryPayload: userDataConsole.buildAffinityHistoryPayload,
    buildAffinityListPayload: userDataConsole.buildAffinityListPayload,
    buildAffinityLogEntries: logConsole.buildAffinityLogEntries,
    buildApiSettingsPayload: apiSettingsConsole.buildApiSettingsPayload,
    buildAuthStatusPayload: webConsoleAuth.buildAuthStatusPayload,
    buildBotPluginManagementPayload: botPluginConsole.buildPayload,
    buildPluginCatalogPayload: pluginCatalogConsole.buildPayload,
    buildConfigBackupPayload: configBackupConsole.buildBackupPayload,
    buildConfigPayload: configPayloadConsole.buildConfigPayload,
    buildConfigRestorePreviewPayload: configBackupConsole.buildRestorePreviewPayload,
    buildDependencyReport: dependencyConsole.buildDependencyReport,
    buildEditableConfigPayload: featureConfigConsole.buildEditableConfigPayload,
    buildFeatureToggleHelpPreviewPayload: featureConfigConsole.buildFeatureToggleHelpPreviewPayload,
    buildFileBrowserHighlightPayload: fileBrowserConsole.buildHighlightPayload,
    buildFileBrowserNodePayload: fileBrowserConsole.buildNodePayload,
    buildFileBrowserTreePayload: fileBrowserConsole.buildTreePayload,
    buildGroupManagementAuditContext: groupManagementConfigSave.buildGroupManagementAuditContext,
    buildGroupManagementEventFeedPayload: groupManagementEventFeed.buildPayload,
    buildGroupManagementJoinRequestsPayload: groupManagementJoinRequests.buildPayload,
    buildGroupManagementLogEntries: logConsole.buildGroupManagementLogEntries,
    buildGroupManagementMembersPayload: groupManagementMembers.buildPayload,
    buildGroupManagementPayload: groupManagementPayload.buildPayload,
    buildGroupManagementTitleApplicationsPayload: groupManagementTitleApplications.buildPayload,
    buildHealthPayload: overviewConsole.buildHealthPayload,
    buildHelpDiyHistoryPayload: options.helpDiyConsole?.buildHistoryPayload,
    buildHelpDiyImportPreviewPayload: options.helpDiyConsole?.buildImportPreviewPayload,
    buildHelpDiyPayload: options.helpDiyConsole?.buildPayload,
    buildImageMonitorLogPayload: imageMonitorConsole.buildLogPayload,
    buildImageMonitorUsageTrendPayload: usageTrendConsole.buildImageMonitorUsageTrendPayload,
    buildLocalMemeScanPayload: memeConsole.buildLocalScanPayload,
    buildLogsPayload: logConsole.buildLogsPayload,
    diagnoseBotLogsPayload: logDiagnosisConsole.diagnosePayload,
    buildOverviewPayload: overviewConsole.buildOverviewPayload,
    buildPluginSettingsPayload: pluginSettingsConsole.buildPluginSettingsPayload,
    buildPokeImageSummaryTrendPayload: usageTrendConsole.buildPokeImageSummaryTrendPayload,
    buildProfileDetailPayload: userDataConsole.buildProfileDetailPayload,
    buildProfilesPayload: userDataConsole.buildProfilesPayload,
    buildQqSimulatorPreviewPayload: qqSimulatorConsole.buildQqSimulatorPreviewPayload,
    buildQqSimulatorScenarioBackupListPayload: qqSimulatorConsole.buildQqSimulatorScenarioBackupListPayload,
    buildQqSimulatorSendPayload: qqSimulatorConsole.buildQqSimulatorSendPayload,
    buildSandboxConfigStatusPayload: sandboxConsole.buildSandboxConfigStatusPayload,
    buildSandboxPromptPreviewPayload: sandboxConsole.buildSandboxPromptPreviewPayload,
    buildSandboxWebReadPayload: sandboxConsole.buildSandboxWebReadPayload,
    buildSessionDebugPayload: userDataConsole.buildSessionDebugPayload,
    buildSessionListPayload: userDataConsole.buildSessionListPayload,
    buildSkillConfigEditorPayload: pluginSettingsConsole.buildSkillConfigEditorPayload,
    buildUsageLogEntries: logConsole.buildUsageLogEntries,
    buildUsageTrendPayload: usageTrendConsole.buildUsageTrendPayload,
    buildWebConsoleAuthCookieClearHeader: webConsoleAuth.buildWebConsoleAuthCookieClearHeader,
    bulkEnableGroupManagementConfig: groupManagementBulkActions.bulkEnableConfig,
    cleanupImageMonitorNonMemePayload: imageMonitorConsole.cleanupNonMemePayload,
    cleanupImageMonitorUnmatchedMemePayload: imageMonitorConsole.cleanupUnmatchedMemePayload,
    clearDependencyInstallHistory: dependencyConsole.clearDependencyInstallHistory,
    clearGroupManagementWarningPayload: groupManagementMemberWarnings.clearWarningPayload,
    clearHelpDiyHistory: options.helpDiyConsole?.clearHistory,
    clearQqSimulatorScenariosPayload: qqSimulatorConsole.clearQqSimulatorScenariosPayload,
    convertGroupManagementLogToScenarioPayload: qqSimulatorConsole.convertGroupManagementLogToScenarioPayload,
    createDependencyInstallTask: dependencyConsole.createDependencyInstallTask,
    createPluginCatalogInstallTask: pluginCatalogConsole.createInstallTask,
    createFileBrowserDirectory: fileBrowserConsole.createDirectory,
    createFileBrowserFile: fileBrowserConsole.createFile,
    deleteBotPlugin: botPluginConsole.deletePlugin,
    deleteFileBrowserNode: fileBrowserConsole.deleteNode,
    deleteHelpDiyHistoryItem: options.helpDiyConsole?.deleteHistoryItem,
    deleteHelpDiyImage: options.helpDiyConsole?.deleteImage,
    deleteQqSimulatorScenarioPayload: qqSimulatorConsole.deleteQqSimulatorScenarioPayload,
    deleteUserProfile: userDataConsole.deleteUserProfile,
    enqueueQqSimulatorScenarioTask: qqSimulatorConsole.enqueueQqSimulatorScenarioTask,
    exportDataAsText: logConsole.exportDataAsText,
    findAffinityLogEntry: logConsole.findAffinityLogEntry,
    findImageMonitorLogEntry: imageMonitorConsole.findLogEntry,
    findUsageLogEntry: logConsole.findUsageLogEntry,
    generateKnowledgeBaseFromWebPayload: sandboxConsole.generateKnowledgeBaseFromWebPayload,
    getDependencyInstallTask: dependencyConsole.getDependencyInstallTask,
    getPluginCatalogInstallTask: pluginCatalogConsole.getTask,
    getHelpDiyTemplates: options.helpDiyConsole?.getTemplates,
    getHttpErrorStatus: httpUtils.getHttpErrorStatus,
    getSkillSecretSourceConfigs: pluginSettingsConsole.getSkillSecretSourceConfigs,
    importQqSimulatorScenariosPayload: qqSimulatorConsole.importQqSimulatorScenariosPayload,
    isBootstrapApiPath: webConsoleAuth.isBootstrapApiPath,
    isBootstrapSetupRequest: webConsoleAuth.isBootstrapSetupRequest,
    isLogExportType: logConsole.isLogExportType,
    listDependencyInstallTasks: dependencyConsole.listDependencyInstallTasks,
    listPluginCatalogInstallTasks: pluginCatalogConsole.listTasks,
    listQqSimulatorScenariosPayload: qqSimulatorConsole.listQqSimulatorScenariosPayload,
    loginWebConsole: webConsoleAuth.loginWebConsole,
    manageFeatureToggle: featureConfigConsole.manageFeatureToggle,
    normalizeGroupManagementId: groupManagementCommon.normalizeGroupManagementId,
    normalizeImageContentTypeSafe: remoteImageProxy.normalizeImageContentType,
    parseRequestBody: httpUtils.parseRequestBody,
    proxyRemoteImageSafe: remoteImageProxy.proxyImage,
    pullRemoteMemeToLocal: memeConsole.pullRemoteToLocal,
    readFileBrowserFile: fileBrowserConsole.readFile,
    refreshConsoleBackgroundCache: consoleBackground.refreshCache,
    rejectGroupManagementJoinRequestPayload: groupManagementJoinRequests.rejectPayload,
    rejectGroupManagementTitleApplicationPayload: groupManagementTitleApplications.rejectPayload,
    renameFileBrowserNode: fileBrowserConsole.renameNode,
    requireAuth: webConsoleAuth.requireAuth,
    requireCsrf: webConsoleAuth.requireCsrf,
    requireLogsExposed: logConsole.requireLogsExposed,
    requireSameOrigin: webConsoleAuth.requireSameOrigin,
    refreshPluginCatalogRemoteSource: pluginCatalogConsole.refreshRemoteCatalog,
    resetAffinityRecord: userDataConsole.resetAffinityRecord,
    resetSessionMessagesOnly: userDataConsole.resetSessionMessagesOnly,
    resetSessionRecord: userDataConsole.resetSessionRecord,
    restoreConfigBackupPayload: configBackupConsole.restoreBackupPayload,
    restoreMaskedSkillConfigSecrets: pluginSettingsConsole.restoreMaskedSkillConfigSecrets,
    restoreQqSimulatorScenarioBackupPayload: qqSimulatorConsole.restoreQqSimulatorScenarioBackupPayload,
    rollbackGroupManagementConfigPayload: groupManagementConfigSave.rollbackGroupManagementConfigPayload,
    runSandboxChat: sandboxConsole.runSandboxChat,
    saveApiSettings: apiSettingsConsole.saveApiSettings,
    saveBase64Image: options.helpDiyConsole?.saveImage,
    saveEditableConfig: featureConfigConsole.saveEditableConfig,
    saveGroupManagementConfig: groupManagementConfigSave.saveGroupManagementConfig,
    saveGroupManagementDefaultsConfig: groupManagementSettings.saveDefaultsConfig,
    saveGroupManagementSafetyPayload: groupManagementSettings.saveSafetyPayload,
    saveHelpDiyPayload: options.helpDiyConsole?.savePayload,
    savePluginSettings: pluginSettingsConsole.savePluginSettings,
    saveQqSimulatorScenarioPayload: qqSimulatorConsole.saveQqSimulatorScenarioPayload,
    searchFileBrowserContent: fileBrowserConsole.searchContent,
    sendBinary: httpUtils.sendBinary,
    sendJson: httpUtils.sendJson,
    sendText: httpUtils.sendText,
    serializeDependencyInstallTask: dependencyConsole.serializeDependencyInstallTask,
    serializePluginCatalogInstallTask: pluginCatalogConsole.serializeTask,
    serveConsoleBackgroundImage: consoleBackground.serveImage,
    serveGroupManagementEventStream: groupManagementEventFeed.serveStream,
    serveGroupWelcomeImage: groupWelcomeConsole.serveImage,
    serveImageMonitorLocalImage: imageMonitorConsole.serveLocalImage,
    serveStatic: staticConsole.serveStatic,
    testApiConnection: apiSettingsConsole.testApiConnection,
    testImageApiConnection: apiSettingsConsole.testImageApiConnection,
    testImageMonitorApiConnection: apiSettingsConsole.testImageMonitorApiConnection,
    testMemeApiConnection: memeConsole.testMemeApiConnection,
    testSearchApiConnection: apiSettingsConsole.testSearchApiConnection,
    toggleFeatureState: featureConfigConsole.toggleFeatureState,
    validateSkillConfigPayload: pluginSettingsConsole.validateSkillConfigPayload,
    writeFileBrowserFile: fileBrowserConsole.writeFile,
  };

  assertHandlerContext(context);
  return context;
}
